# Generated by Django 4.1 on 2022-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAllowed',
            field=models.BooleanField(default=True),
        ),
    ]
